<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Product related posts template
 *
 * @var $block \Magefan\Blog\Block\Catalog\Product\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <hr>
    <div class="related-posts">
        <h4>
            <?php echo __('Related articles') ?>
        </h4>
        <ul>
            <?php foreach ($_postCollection as $_post) { ?>
                <li>
                    <a href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()); ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <?php } ?>
<?php } ?>