<?php 
$categories = $block->getStoreCategories(true,false,true);
//$categories = $block->getCategoryCollection();
$getCategory = $block->getCurrentCategory();
if(isset($getCategory)) { $currentCategory = $getCategory->getId(); 
$parentIdentifer = explode('/', $getCategory->getPath()); }
if(isset($parentIdentifer[2])) { $parentIdentiferIdLevel1 = $parentIdentifer[2]; }
if(isset($parentIdentifer[3])) { $parentIdentiferIdLevel2 = $parentIdentifer[3]; }
if(isset($parentIdentifer[4])) { $parentIdentiferIdLevel3 = $parentIdentifer[4]; }
?>
<div class="sidebar-category-list">
	<ul class="accordion">
	<?php
	$i='';
	foreach($categories as $category){
	 	if($category->getName() !='View All' && $category->getName() !='Ebay' && $category->getName()!='Exhibition') {
	?>
		<li>
		    <a class="toggle toggle-top" href="javascript:void(0);">
		    	<!-- category name level 1 -->
				<?php 
					if(isset($parentIdentiferIdLevel1)&&$parentIdentiferIdLevel1 === $category->getId()) {
						echo $category->getName();
					} else {
						echo $category->getName();
					}
				?>
				<?php
					if(isset($parentIdentiferIdLevel1)&&$parentIdentiferIdLevel1 === $category->getId()) {
				  		if($category->hasChildren()){ echo'<i class="feather icon-minus"></i>'; }
				 	} else {
				  		if($category->hasChildren()){ echo'<i class="feather icon-plus"></i>'; }
				  	} 
				?>
		    </a>
		    <?php if(isset($parentIdentiferIdLevel1)&&$parentIdentiferIdLevel1 === $category->getId()) { ?>
		    <div class="<?php if($category->getName()==='Age') echo 'age-item-container ';?>inner opened">
		    <?php } else { ?>
			<div class="<?php if($category->getName()==='Age') echo 'age-item-container ';?>inner">
		    <?php } ?>

		    	<?php if($category->hasChildren()) {
			     	$cats1 = $block->getCategorymodel($category->getId());
			     	$childCats1 = $cats1->getChildrenCategories();
			     	$childCats1->clear();
			     	$childCats1->addAttributeToFilter('include_in_menu',1);
			     	$childCats1->load();
			     	$childCats1_sorter = array();
			    ?>
				<?php
				switch ($category->getName()) {
				    case "Collections":
				      	
				    	foreach($childCats1 as $childCat1) {
							$cats2 = $block->getCategorymodel($childCat1->getId());
	     					$childCats2 = $cats2->getChildrenCategories();
	     					$childCats2->clear();
	 						$childCats2->addAttributeToFilter('include_in_menu',1);
	 						$childCats2->load();
	     					$childCats2_sorter = array();

	     					if(!$childCat1->hasChildren()){ 
			        			echo '<a class="collection-items" href="'.$childCat1->getUrl().'">'; 
			        		} else {
			        			echo '<a class="collection-items toggle" href="#">';
			        		}
	    	 				echo (isset($parentIdentiferIdLevel2))?($parentIdentiferIdLevel2 === $childCat1->getId()?'<strong>'.$childCat1->getName().'</strong>':$childCat1->getName()):$childCat1->getName();
							//echo '<span class="icon-container-level2">';
							 	if(isset($parentIdentiferIdLevel2)&&$parentIdentiferIdLevel2 === $childCat1->getId()) {
							 		if($childCat1->hasChildren()){ echo'<i class="feather icon-minus"></i>'; }
							 	} else {
							 		if($childCat1->hasChildren()){ echo'<i class="feather icon-plus"></i>'; }
							 	}
							
		    	 			echo '</a>';
		    	 			if(isset($parentIdentiferIdLevel2)&&$parentIdentiferIdLevel2 === $childCat1->getId()) { 
		    						echo '<ul class="inner inner-level2 opened">';
		    						} else {
									echo '<ul class="inner inner-level2">';
		    					}
				    	 		foreach($childCats2 as $childCat2) {
									echo '<li>';
						    	 		echo '<a class="category-two-link" href="'.$childCat2->getUrl().'">';
							    	 		if (isset($currentCategory)&&$childCat2->getId() === $currentCategory) {
						    	 				echo '<strong>'.$childCat2->getName().'</strong>';
						    	 			} else {
						    	 				echo $childCat2->getName();
						    	 			}
						    	 		echo '</a>';	    	 			
						    	 	echo '</li>';
						     	}
	   						echo '</ul>';

			     		} // closes foreach($childCats1 as $childCat1)
				        break;
				    case "Age":
				        foreach($childCats1 as $childCat1) {
							$cats2 = $block->getCategorymodel($childCat1->getId());
	     					$childCats2 = $cats2->getChildrenCategories();
	     					$childCats2->clear();
     						$childCats2->addAttributeToFilter('include_in_menu',1);
     						$childCats2->load();
	     					$childCats2_sorter = array();

	     					if(!$childCat1->hasChildren()){ 
			        			echo '<a class="age-items" href="'.$childCat1->getUrl().'">'; 
			        		} else {
			        			echo '<a class="age-items toggle" href="#">';
			        		}
	    	 				echo (isset($parentIdentiferIdLevel2))?($parentIdentiferIdLevel2 === $childCat1->getId()?'<strong>'.$childCat1->getName().'</strong>':$childCat1->getName()):$childCat1->getName();
							//echo '<span class="icon-container-level2">';
							 	if(isset($parentIdentiferIdLevel2)&&$parentIdentiferIdLevel2 === $childCat1->getId()) {
							 		if($childCat1->hasChildren()){ echo'<i class="feather icon-minus"></i>'; }
							 	} else {
							 		if($childCat1->hasChildren()){ echo'<i class="feather icon-plus"></i>'; }
							 	}
							
		    	 			echo '</a>';
		    				if($childCat1->getName() === '19th-century') {
		    					if(isset($parentIdentiferIdLevel2)&&$parentIdentiferIdLevel2 === $childCat1->getId()) { 
			    						echo '<ul class="inner age inner-level2 opened">';
			    						} else {
										echo '<ul class="inner age inner-level2">';
			    					}
					    	 		foreach($childCats2 as $childCat2) {
										echo '<li>';
							    	 		echo '<a class="category-two-link" href="'.$childCat2->getUrl().'">';
								    	 		if (isset($currentCategory)&&$childCat2->getId() === $currentCategory) {
							    	 				echo '<strong>'.$childCat2->getName().'</strong>';
							    	 			} else {
							    	 				echo $childCat2->getName();
							    	 			}
							    	 		echo '</a>';	    	 			
							    	 	echo '</li>';
							     	}
		   						echo '</ul>';
		    				}
	     				}//closes foreach($childCats1 as $childCat1) L:97
				        break;
				    case "Artist":
				    ?>
				    	<ul>
							<?php 
								foreach($childCats1 as $childCat1) {
									$productCount = $childCat1->getProductCount();
									$string = $childCat1->getName();
		                  			$pieces = explode(' ', $string);
		                  			$last_name = array_pop($pieces);
		                  			$name_remainder = implode(' ',$pieces);
		                  			$artist_sorter[$last_name] = array('first_names'=>$name_remainder,'url'=>$childCat1->getUrl(),'id'=>$childCat1->getId(),'productCount'=>$childCat1->getProductCount());
						     		// $cats2 = $block->getCategorymodel($childCat1->getId());
					     			// $childCats2 = $cats2->getChildrenCategories();

								}
								if ($category->getName() === 'Artist') {
					    			ksort($artist_sorter,SORT_NATURAL);	
					    		}
					    	?>
							<?php
					    		foreach ($artist_sorter as $surname => $properties){
							    	 	$url = $properties['url'];
							    	 	$id = $properties['id'];
							    	 	$firstNames = $properties['first_names'];
							    	 	$productCount = $properties['productCount'];
						    	 		if ($productCount >= 1) {
						    	 			echo '<li>';
								    	 		echo '<a class="category-two-link" href="'.$url.'">';
								    	 			if (isset($currentCategory)&&$id === $currentCategory) {
								    	 				echo '<span class="current-category surname">'.$surname.'</span>';
								    	 				if ($firstNames !='') {
								    	 					echo '<span class="seperator">, </span>';
								    	 				}
								    	 				echo '<span class="firstNames">'.$firstNames.'</span';
								    	 			} else {
								    	 				echo '<span class="surname">'.$surname.'</span>';
								    	 				if ($firstNames !='') {
								    	 					echo '<span class="seperator">, </span>';
								    	 				}
								    	 				echo '<span class="firstNames">'.$firstNames.'</span>';
								    	 			}
								    	 		echo '</a>';
								    	 	echo '</li>';
							    	 	}
							    	}
							?>
						</ul> <!-- closes artist UL-->
				    <?php
				        break;
				    default:
						foreach($childCats1 as $childCat1) {
							$productCount = $childCat1->getProductCount();
							$childCats1_sorter[$childCat1->getName()] = array('url'=>$childCat1->getUrl(),'id'=>$childCat1->getId(),'productCount'=>$childCat1->getProductCount());
				     		// $cats2 = $block->getCategorymodel($childCat1->getId());
			     			// $childCats2 = $cats2->getChildrenCategories();		
				    	}
			    		if ($category->getName() != 'Age' || $category->getName() != 'Collections') {
			    			ksort($childCats1_sorter,SORT_NATURAL);	
			    		}
			    		echo '<ul>';
	    				foreach ($childCats1_sorter as $name => $properties) {
				    	 	$url = $properties['url'];
				    	 	$id = $properties['id'];
				    	 	$productCount = $properties['productCount'];
				    	 	if ($category->getName() === 'Artist') {
				    	 		if ($productCount >= 1) {
						    	 	echo '<li>';
						    	 		echo '<a class="category-two-link" href="'.$url.'">';
						    	 			if (isset($currentCategory)&&$id === $currentCategory) {
						    	 				echo '<strong>'.$name.'</strong>';
						    	 			} else {
						    	 				echo $name;
						    	 			}
						    	 		echo '</a>';
						    	 	echo '</li>';
					    	 	}
				    	 	} else {
				    	 		
								echo '<li>';
					    	 		echo '<a class="category-two-link" href="'.$url.'">';
					    	 			if (isset($currentCategory)&&$id === $currentCategory) {
					    	 				echo '<strong>'.$name.'</strong>';
					    	 			} else {
					    	 				echo $name;
					    	 			}
					    	 		echo '</a>';
					    	 	echo '</li>';
				    	 	}
				    	}
				    	echo '</ul>';
				}// end main switch statement
				?>
			<?php } // closes if($category->hasChildren() L:37 ?>
		    </div>
		</li>
	<?php
		}//closes if($category->getName() !='View All')
	$i++; 
	} //closes foreach($categories as $category)
	?>

	</ul><!-- closes <ul class="accordion"> -->
</div><!-- closes .sidebar-category-list -->