<?php 
	// check if URL is HTTP or HTTPS
	if ( (! empty($_SERVER['REQUEST_SCHEME']) && $_SERVER['REQUEST_SCHEME'] == 'https') ||
		     (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ||
		     (! empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == '443') ) {
		    $server_request_scheme = 'https';
		} else {
		    $server_request_scheme = 'http';
		}

	// form image URL
	$imageUrl = $server_request_scheme.'://'.$_SERVER['SERVER_NAME'].'/pub/media/wysiwyg/exhibition/'.$block->getData('latestcollectionsImage') ;

?>
<div class="latest-collections-panel">
	<a href="/<?php if($block->getData('latestcollectionsLink')) {echo $block->getData('latestcollectionsLink');} ?>">
		<?php if($block->getData('latestcollectionsImage')) { ?>
		 	<img src="<?php echo $imageUrl; ?>" width="357" />
		<?php } ?>
		<?php if($block->getData('latestcollectionsTitle')) { ?>
			<h3><?php echo $block->getData('latestcollectionsTitle'); ?></h3>
		<?php } ?>
		<?php if($block->getData('latestcollectionsText')) { ?>
			<p><?php echo $block->getData('latestcollectionsText'); ?></p>
		<?php } ?>
		<p><a class="read-more" href="/<?php if($block->getData('latestcollectionsLink')) {echo $block->getData('latestcollectionsLink');} ?>">View All</a></p>
	</a>
</div>
