<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('size', 'getChildHtml')):?>
    <?php $layout = $block->getLayout(); ?>
	<div class="size-content">
		<b>Size: </b>
		<?php foreach ($detailedInfoGroup as $name):?>
			<?php
				$html = $layout->renderElement($name);
				if (!trim($html)) {
					continue;
				}
			?>
			<span>
				<?php /* @escapeNotVerified */ echo $html; ?>
			</span>
			<?php if($name == 'product.info.height') { ?> 
				<span class="sizex">x</span>
			<?php } ?>
		<?php endforeach;?>
	</div>
<?php endif; ?>
