<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Featured
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <h3><?php echo __('Featured Posts') ?></h3>
    <ul>
        <?php foreach ($_postCollection as $_post) { ?>
            <li class="item">
                <a class="post-item-link"
                   href="<?php echo $_post->getPostUrl() ?>">
                    <?php echo $block->escapeHtml($_post->getTitle()) ?>
                </a>
            </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>