<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<button class="sw-btn-base sw-btn-secondary sw-fill-secondary">
	<a href="#"
		 title="<?= $block->escapeHtml(__('Remove item')) ?>"
		 class=""
		 data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>
		 <?= /* @escapeNotVerified */ __('Remove item') ?>
	</a>
</button>
