<div class="dropdown">
	<button class="dropdown-toggle my-account-header-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<span>My Account</span>
		<!-- <i data-feather="user"></i>
		<i class="feather icon-chevron-down"></i> -->
	</button>
	<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		<?php echo $block->getChildHtml(); ?>	
	</div>
</div>
