<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<div class="logo-container">
	<a class="" href="<?= $block->getUrl('') ?>" title="Somerset &amp; Wood Fine Art">
		<img class="img-responsive" src="<?= /* @escapeNotVerified */ $block->getUrl() ?>pub/media/logo/default/somersetandwood-logo.png" sizes="(max-width: 768px) 90vw, (min-width: 992px) 600px"
	srcset="<?= /* @escapeNotVerified */ $block->getUrl() ?>pub/media/logo/default/somersetandwood-logo-small.png 400w, <?= /* @escapeNotVerified */ $block->getUrl() ?>pub/media/logo/default/somersetandwood-logo.png 600w, <?= /* @escapeNotVerified */ $block->getUrl() ?>pub/media/logo/default/somersetandwood-logo-2x.png 1200w, <?= /* @escapeNotVerified */ $block->getUrl() ?>pub/media/logo/default/somersetandwood-logo-3x.png 1800w" alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>" />
	</a>
</div>
	
