<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $image = 'new_products_content_widget_grid';
    $image_x2 = 'new_products_content_widget_grid_x2';
    $image_x3 = 'new_products_content_widget_grid_x3';
    $items = $block->getProductCollection()->getItems();
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_imageHelper = $this->helper(Magento\Catalog\Helper\Image::class);
    $placeholder_image = '/pub/media/logo/default/somersetandwood-placeholder-compressed.png';

    $productImageURL = '';
    $productImageDimensions = '';
    $productImageWidth = '';
    $productImageHeight = '';

    $productImageURL_x2 = '';
    $productImageDimensions_x2 = '';
    $productImageWidth_x2 = '';
    $productImageHeight_x2 = '';

    $productImageURL_x3 = '';
    $productImageDimensions_x3 = '';
    $productImageWidth_x3 = '';
    $productImageHeight_x3 = '';
?>
    <h2 class="featured-heading">Featured Artwork</h2>    
     <div class="featured-products">   
     <?php $iterator = 0; ?>
        <?php foreach ($items as $_item): ?>
            <?php

                $productImageURL = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_item, $image)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL);
                $productImageDimensions = getimagesize($productImagePath);
                // $productImageDimensions = getimagesize($productImageURL);
                $productImageWidth = $productImageDimensions[0];
                $productImageHeight = $productImageDimensions[1];
                
                $productImageURL_x2 = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_item, $image_x2)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath_x2  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL_x2);
                $productImageDimensions_x2 = getimagesize($productImagePath_x2);
                // $productImageDimensions_x2 = getimagesize($productImageURL_x2);
                $productImageWidth_x2 = $productImageDimensions_x2[0];
                $productImageHeight_x2 = $productImageDimensions_x2[1];
                
                $productImageURL_x3 = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_item, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath_x3  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL_x3);
                $productImageDimensions_x3 = getimagesize($productImagePath_x3);
                // $productImageDimensions_x3 = getimagesize($productImageURL_x3);
                $productImageWidth_x3 = $productImageDimensions_x3[0];
                $productImageHeight_x3 = $productImageDimensions_x3[1];

                if($productImageWidth > $productImageHeight) {
                    $orientation = 'landscape';
                    $landscapeImage = $productImageURL;
                    $landscapeImage_x2 = $productImageURL_x2;
                    $landscapeImage_x3 = $productImageURL_x3;

                } elseif ($productImageWidth < $productImageHeight) {
                    $orientation = 'portrait';
                    $difference = 249 - $productImageWidth;
                    $difference_x2 = 498 - $productImageWidth_x2;
                    $difference_x3 = 747 - $productImageWidth_x3;

                    $newHeight = $productImageHeight + $difference;
                    $newHeight_x2 = $productImageHeight_x2 + $difference_x2;
                    $newHeight_x3 = $productImageHeight_x3 + $difference_x3;

                    $resizedPortraitImageUrl = $_imageHelper->init($_item, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(249, ($newHeight+10))
                                        ->getUrl();
                    $resizedPortraitImageUrl_x2 = $_imageHelper->init($_item, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(498, ($newHeight_x2+10))
                                        ->getUrl();
                    $resizedPortraitImageUrl_x3 = $_imageHelper->init($_item, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(498, ($newHeight_x3+10))
                                        ->getUrl();

                     
                } elseif($productImageWidth === $productImageHeight) {

                    $orientation = 'square';
                    $squareImage = $productImageURL;
                    $squareImage_x2 = $productImageURL_x2;
                    $squareImage_x3 = $productImageURL_x3;

                } else {
                    $orientation = 'placeholder';
                }
            ?>
                <div class="featured-container">
                    <div class="featured-products-image">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="">
                            <?php if($orientation === 'portrait') { ?>
                                <img class="lazyload" loading="lazy" data-src="<?= $resizedPortraitImageUrl; ?>" data-srcset="<?= $resizedPortraitImageUrl_x2; ?> 2x, <?= $resizedPortraitImageUrl_x3; ?> 3x" />
                            <?php } elseif($orientation === 'landscape') { ?>
                                <img class="lazyload" loading="lazy" data-src="<?= $landscapeImage; ?>" data-srcset="<?= $landscapeImage_x2; ?> 2x, <?= $landscapeImage_x3; ?> 3x" />
                            <?php } elseif($orientation ==='square') { ?>
                                <img class="lazyload" loading="lazy" data-src="<?= $squareImage; ?>" data-srcset="<?= $squareImage_x2; ?> 2x, <?= $squareImage_x3; ?> 3x" />
                            <?php } ?>
                        </a>                        
                    </div>
                    <div class="featured-products-details">
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                        <?php
                            if ($_item->isSaleable()) { 
                                echo $block->getProductPriceHtml($_item, $type);
                            }else {
                                echo '<div class="price-box sold"><span class="circle"></span><span class="text">SOLD</span></div>';
                            }
                        ?>  
                    </div>                                
                </div>
        <?php $iterator++; ?>
        <?php endforeach; ?>
    </div>            
<?php endif;?>
