<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<h1><img class="img-responsive" src="images/somersetandwood-logo.png" srcset="images/somersetandwood-logo.png 1x, images/somersetandwood-logo-2x.png 2x" alt="Somerset & Wood" /></h1>
<div class="content">
	<h2>Maintenance Mode</h2>
	<p>We are currently fixing an issue with our site. Our team are working to get this resolved as quickly as possible and we will be back up and running soon.</p>
	<p>In the meantime you can contact us at <a href="mailto:enquiries@somersetandwood.com">enquiries@somersetandwood.com</a>.</p>
	<p>Thank you for your patience.</p>
</div>
