<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<h1><img class="img-responsive" src="images/somersetandwood-logo.png" srcset="images/somersetandwood-logo.png 1x, images/somersetandwood-logo-2x.png 2x" alt="Somerset & Wood" /></h1>
<div class="content">
	<h2>We are currently working on upgrading our site.</h2>
	<p>Sorry for the inconvenience. Our new and improved site will be up and running shortly, so please check back soon.</p>
	<p>In the meantime, you can contact us via email at <a href="mailto:enquiries@somersetandwood.com">enquiries@somersetandwood.com</a>, by telephone on +44 (0)1225 784177 or view our current stock <a href="https://www.ebay.co.uk/str/somersetandwoodfineart">here</a>.</p>
</div>