<?php

$sold_artworks = $block->getOutofstockProductCollection();
//echo $sold_artworks->getSelect()->group('product_id');
//$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_imageHelper = $this->helper(Magento\Catalog\Helper\Image::class);
$placeholder_image = '/media/logo/default/somersetandwood-placeholder-compressed.png';
?>

<?php if (!$sold_artworks->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php if ($block->getPagerHtml()): ?>
    	<div class="sold-products-toolbar toolbar top"><?php echo $block->getPagerHtml(); ?></div>
	<?php endif ?>
	<div class="sold-container">
		<?php $iterator = 1; ?>
        <ol class="">
		<?php 
			foreach ($sold_artworks as $sold_artwork) {
			  	$title = $sold_artwork->getName();
			  	$id = $sold_artwork->getId();
			  	$url = $sold_artwork->getProductUrl();

			  	// choose which image
			  	$image = 'category_page_grid';
			  	$image_x2 = 'category_page_grid_x2';
			  	$image_x3 = 'category_page_grid_x3';

			  	// set variables scope
			  	$orientation = '';
			  	$landscapeImage = '';
			  	$landscapeImage_x2 ='';
			  	$landscapeImage_x3 ='';
			  	$squareImage = '';
                $squareImage_x2 = '';
                $squareImage_x3 = '';
			  	$newHeight ='';
			  	$newHeight_x2 ='';
			  	$newHeight_x3 ='';
			  	$resizedPortraitImageUrl ='';
			  	$resizedPortraitImageUrl_x2 ='';
			  	$resizedPortraitImageUrl_x3 ='';

			  	$productImageURL = $_imageHelper->init($sold_artwork, $image)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL);
                $productImageDimensions = getimagesize($productImagePath);
                $productImageWidth = $productImageDimensions[0];
                $productImageHeight = $productImageDimensions[1];
                
                $productImageURL_x2 = $_imageHelper->init($sold_artwork, $image_x2)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath_x2  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL_x2);
                $productImageDimensions_x2 = getimagesize($productImagePath_x2);
                $productImageWidth_x2 = $productImageDimensions_x2[0];
                $productImageHeight_x2 = $productImageDimensions_x2[1];
                
                $productImageURL_x3 = $_imageHelper->init($sold_artwork, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                $productImagePath_x3  = $_SERVER['DOCUMENT_ROOT'].'/pub'.str_replace("https://somersetandwood.com", "", $productImageURL_x3);
                $productImageDimensions_x3 = getimagesize($productImagePath_x3);
                $productImageWidth_x3 = $productImageDimensions_x3[0];
                $productImageHeight_x3 = $productImageDimensions_x3[1];


				if($productImageWidth > $productImageHeight) {
	                $orientation = 'landscape';
	                $landscapeImage = $productImageURL;
                    $landscapeImage_x2 = $productImageURL_x2;
                    $landscapeImage_x3 = $productImageURL_x3;

	            } elseif ($productImageWidth < $productImageHeight) {
	                $orientation = 'portrait';
	                $difference = 249 - $productImageWidth;
                    $difference_x2 = 498 - $productImageWidth_x2;
                    $difference_x3 = 747 - $productImageWidth_x3;

                    $newHeight = $productImageHeight + $difference;
                    $newHeight_x2 = $productImageHeight_x2 + $difference_x2;
                    $newHeight_x3 = $productImageHeight_x3 + $difference_x3;

                    $resizedPortraitImageUrl = $_imageHelper->init($sold_artwork, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(249, ($newHeight+10))
                                        ->getUrl();
                    $resizedPortraitImageUrl_x2 = $_imageHelper->init($sold_artwork, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(498, ($newHeight_x2+10))
                                        ->getUrl();
                    $resizedPortraitImageUrl_x3 = $_imageHelper->init($sold_artwork, $image_x3)
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(498, ($newHeight_x3+10))
                                        ->getUrl();
	            } elseif($productImageWidth === $productImageHeight) {
	                $orientation = 'square';
                    $squareImage = $productImageURL;
                    $squareImage_x2 = $productImageURL_x2;
                    $squareImage_x3 = $productImageURL_x3;
	            } else {
	                $orientation = 'placeholder';
	            }
	            ?>

	            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="">' : '</li><li class="">'; ?>
	            	<div class="image-container">
						<a href="<?= /* @escapeNotVerified */ $sold_artwork->getProductUrl() ?>" class="" tabindex="-1">
                        <?php if($orientation === 'portrait') { ?>
                            <img class="lazyload" loading="lazy" width="249" style="width: 249px;"  data-src="<?= $resizedPortraitImageUrl; ?>" data-srcset="<?= $resizedPortraitImageUrl_x2; ?> 2x, <?= $resizedPortraitImageUrl_x3; ?> 3x" />
                        <?php } elseif($orientation === 'landscape') { ?>
                            <img class="lazyload" loading="lazy" width="249" style="width: 249px;" data-src="<?= $landscapeImage; ?>" data-srcset="<?= $landscapeImage_x2; ?> 2x, <?= $landscapeImage_x3; ?> 3x" />
                        <?php } elseif($orientation === 'square') { ?>
                        	<img class="lazyload" loading="lazy" width="249" style="width: 249px;" data-src="<?= $squareImage; ?>" data-srcset="<?= $squareImage_x2; ?> 2x, <?= $squareImage_x3; ?> 3x" />
                        <?php } ?>
	                    </a>	            		
	            	</div>
					<div class="title-container">
						<p>
                            <a class=""
                               href="<?= /* @escapeNotVerified */ $sold_artwork->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($sold_artwork, $sold_artwork->getName(), 'name') ?>
                            </a>
                        </p>
					</div>
	            <?= ($iterator == count($sold_artworks)+1) ? '</li>' : '';
			} // end: foreach ($sold_artworks as $sold_artwork)
			?>
		</ol>
	</div><!-- closes .sold-container -->
	<?php if ($block->getPagerHtml()): ?>
    	<div class="sold-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
	<?php endif ?>
<?php endif; ?>